In [1]:
!pip install torch

In [ ]:
# What is PyTorch?
# PyTorch is a Python-based scientific computing package serving two broad purposes:
# A replacement for NumPy to use the power of GPUs and other accelerators.
# An automatic differentiation library that is useful to implement neural networks.

#Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or 
#other specialized hardware to accelerate computing.

In [2]:
import torch
import numpy as np

In [7]:
data = [[1, 2], [3, 4]]
np_array = np.array(data)
type(nd_array)

numpy.ndarray

In [8]:
#Tensors can be created directly from data. The data type is automatically inferred.
tensor_data = torch.tensor(data)
type(tensor_data)

torch.Tensor

In [9]:
tensor_data

tensor([[1, 2],
        [3, 4]])

In [11]:
# From a NumPy array
# Tensors can be created from NumPy arrays (and vice versa - see Bridge with NumPy).

np_to_tensor = torch.from_numpy(np_array)
type(np_to_tensor)

torch.Tensor

In [12]:
np_to_tensor

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [14]:
#torch.ones_like: Returns a tensor filled with the scalar value 1, with the same size as
#input. torch.ones_like(input) is equivalent to torch.ones(input.size(), 
# dtype=input.dtype, layout=input.layout, device=input.device)

tensor_of_values_1 = torch.ones_like(tensor_data) # retains the properties of tensor_data except the values
tensor_of_values_1

tensor([[1, 1],
        [1, 1]])

In [ ]:
# Returns a tensor with the same size as input that is filled with
# random numbers from a uniform distribution on the interval [0, 1). 
# torch.rand_like(input) is equivalent to torch.rand(input.size(), 
# dtype=input.dtype, layout=input.layout, device=input.device).

tensor_uf = torch.rand_like(tensor_data, dtype=torch.float) # overrides the datatype of x_data
tensor_uf

tensor([[0.1180, 0.2127],
        [0.8474, 0.8221]])

In [21]:
# With random or constant values:

# 'shape' is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.
shape = (3, 5)
tensor_ones = torch.ones(shape)
tensor_ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [22]:
tensor_zeros = torch.zeros(4)
tensor_zeros

tensor([0., 0., 0., 0.])

In [25]:
# Returns a tensor filled with random numbers from a uniform distribution
# on the interval [0, 1)
# The shape of the tensor is defined by the variable argument size.

tensor_random  = torch.rand(shape)
tensor_random

tensor([[0.6645, 0.3298, 0.9968, 0.2958, 0.3101],
        [0.8684, 0.7820, 0.3442, 0.9665, 0.6594],
        [0.3402, 0.3210, 0.1342, 0.0169, 0.7498]])

In [26]:
random_tensor = torch.rand(2, 4)
random_tensor

tensor([[0.7584, 0.9668, 0.5933, 0.2479],
        [0.1082, 0.4350, 0.0968, 0.1448]])

In [31]:
# Tensor Attributes
# Tensor attributes describe their shape, datatype, and the device on which they are stored.

print(f"Shape of tensor: {random_tensor.shape}")
print(f"Datatype of tensor: {random_tensor.dtype}")
print(f"Device tensor is stored on: {random_tensor.device}")

Shape of tensor: torch.Size([2, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [36]:
# These tensor operations can be run on the GPU (at typically higher speeds than on a CPU). 
# If you’re using Colab, allocate a GPU by going to Edit > Notebook Settings. GPU is represented by CUDA!
if torch.cuda.is_available():
    random_tensor = random_tensor.to('cuda')
    print(f"Device tensor is stored on: {random_tensor.device}")
else:
    print("CUDA not available on machine")
    print(f"Device tensor is stored on: {random_tensor.device}")

CUDA not available on machine
Device tensor is stored on: cpu


In [44]:
a = torch.ones(4, 5)
a

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [45]:
# Standard numpy-like indexing and slicing:
a[:, 2] = 0
a

tensor([[1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.]])

In [46]:
# Joining tensors You can use torch.cat to concatenate a sequence of tensors 
# along a given dimension. See also torch.stack, another tensor joining op 
# that is subtly different from torch.cat.

torch.cat((a, a, a), dim=1) #1 ---> columns

tensor([[1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1.]])

In [47]:
torch.cat((a, a, a), dim=0) #0 ---> rows

tensor([[1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.]])

In [62]:
#Multiplying tensors

a.mul(a)
print(f"Multiplication of tensor with itself: \n{a.mul(a)}\n")

#Alternative syntax
print(f"This is element-wise multiplication too:\n {a*a}")

Multiplication of tensor with itself: 
tensor([[1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.]])

This is element-wise multiplication too:
 tensor([[1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.]])


In [54]:
a_transpose = a.T #Transpose of a tensor
a_transpose

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [59]:
print(f"Matrix multiplication of 2 tensors: \n {a.matmul(a_transpose)}\n") #a(4,5) * a_transpose(5, 4)
#Alternative syntax
print(f"This is matrix multiplication too: \n{a @ a_transpose}")

Matrix multiplication of 2 tensors: 
 tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

This is matrix multiplication too: 
tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])


In [63]:
b  = torch.ones(2, 5)
b

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [79]:
#In-place operations Operations that have a _ suffix are in-place. For example: x.copy_(y), x.t_(), will change x.

b.t_() #Inplace transpose operation

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [83]:
b

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [84]:
b.add_(4) #inplace addition operation: Adding a tensr 'b' with scalar value

tensor([[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]])

In [91]:
torch.tensor([1, 2, 3, 4, 5]).shape
b.shape

torch.Size([5, 2])

In [92]:
b.add_(torch.tensor([1, 2])) #inplace addition operation: Adding two tensors

tensor([[6., 7.],
        [6., 7.],
        [6., 7.],
        [6., 7.],
        [6., 7.]])

In [98]:
# Bridge with NumPy
# Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

# Tensor to NumPy array
a = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
a_np = a.numpy()
print(f"Tensor: \n{a}\n")
print(f"Numpy array: \n{a_np}")

Tensor: 
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

Numpy array: 
[[1 2 3 4]
 [5 6 7 8]]


In [100]:
#Due to sharing same location, a change in the tensor reflects in the NumPy array.
a.add_(1) #Inplace addition
print(f"Tensor: \n{a}\n")
print(f"Numpy array: \n{a_np}")

Tensor: 
tensor([[2, 3, 4, 5],
        [6, 7, 8, 9]])

Numpy array: 
[[2 3 4 5]
 [6 7 8 9]]


In [102]:
b_np = np.array(5)
b = torch.from_numpy(b_np)
b

tensor(5, dtype=torch.int32)

In [105]:
#Addition of numpy array wth scaler value 1. 'out' denotes the output of addition to be stored in
np.add(b_np, 1, out =b_np) 

array(6)

In [107]:
#Changes in the NumPy array reflects in the tensor.
print(f"Numpy array: \n{b_np}")
print(f"Tensor: \n{b}\n")


Numpy array: 
6
Tensor: 
6

